apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "simplenodeservice-team16-preprod"
  title: "simplenodeservice-team16-preprod"
  description: "Template for the simplenodeservice owned and operated by team16 in environment preprod"
  annotations:
    backstage.io/techdocs-ref: dir:.
    # Not working
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=userinterface'
    'backstage.io/kubernetes-namespace': 'simplenodeservice-team16-preprod'
    argocd/app-name: simplenodeservice-team16-preprod
  links:
    - url: https://github.com/tuanle273/platform-engineering-demo.git
      title: Github Repo
      icon: github
    - url: https://fuzzy-barnacle-7669p46vxc997-80.app.github.dev/simplenodeservice-team16-preprod
      title: "Browse Application"
      icon: subject
    - title: View in ArgoCD
      icon: catalog
      url: https://fuzzy-barnacle-7669p46vxc997-30100.app.github.dev/applications/argocd/simplenodeservice-team16-preprod
    - title: View in Dynatrace
      icon: catalog
      url: https://pse44217.apps.dynatrace.com
    - url: https://community.dynatrace.com
      title: Dynatrace community
      icon: dashboard
spec:
  type: website
  owner: team16
  lifecycle: preprod
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: "team16"
  description: Group for application team team16
spec:
  type: business-unit
  profile:
    displayName: Team Detroit Lions GO GO GO
    email: team01@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  parent: applications
  children: []
#   members: [jdoe]
