apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "simplenodeservice-team01-preprod"
  title: "simplenodeservice-team01-preprod"
  description: "Template for the simplenodeservice owned and operated by team01 in environment preprod"
  annotations:
    backstage.io/techdocs-ref: dir:.
    # Not working
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=userinterface'
    'backstage.io/kubernetes-namespace': 'simplenodeservice-team01-preprod'
    argocd/app-name: simplenodeservice-team01-preprod
  links:
    - url: https://github.com/tuanle273/platform-engineering-demo.git
      title: Github Repo
      icon: github
    - url: https://fuzzy-barnacle-7669p46vxc997-80.app.github.dev/simplenodeservice-team01-preprod
      title: "Browse Application"
      icon: subject
    - title: View in ArgoCD
      icon: catalog
      url: https://miniature-invention-r6jx6r46xwph5jj-30100.app.github.dev/applications/argocd/simplenodeservice-team01-preprod
    - title: View in Dynatrace
      icon: catalog
      url: https://pse44217.apps.dynatrace.com
    - url: https://community.dynatrace.com
      title: Dynatrace community
      icon: dashboard
spec:
  type: website
  owner: team01
  lifecycle: preprod
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: "team01"
  description: Group for application team team01
spec:
  type: business-unit
  profile:
    displayName: Team 01
    email: team01@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  parent: applications
  children: []
#   members: [jdoe]
